docker container stop docker_training_nginx_simple
docker container stop docker_training_nginx_detached
docker container stop docker_training_ubuntu
docker container stop docker_training_sqlserver
docker container stop docker_training_nanoserver
docker system prune