docker container stop docker_traning_nginx_simple
docker container stop docker_traning_nginx_detached
docker container stop docker_traning_ubuntu
docker container stop docker_traning_sqlserver
docker container stop docker_traning_nanoserver
docker system prune