version: '3.5'
services:

  prometheus:
    image: prom/prometheus
    container_name: 'docker_training_prometheus'
    ports:
      - '9090:9090'
    networks:
      - docker_training_network_advancedwebapp
    volumes:
      - "D:/DockerTraining/src/05_Orchestrating_Systems_with_Docker/AdvancedWebApp_Orchestration/Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"

  grafana:
    image: 'grafana/grafana'
    container_name: 'docker_training_grafana'
    ports:
      - '3000:3000'
    networks:
      - docker_training_network_advancedwebapp
    volumes:
      - "D:/DockerTraining/src/05_Orchestrating_Systems_with_Docker/AdvancedWebApp_Orchestration/Grafana/provisioning:/etc/grafana/provisioning"
      - "D:/DockerTraining/src/05_Orchestrating_Systems_with_Docker/AdvancedWebApp_Orchestration/Grafana/dashboards:/var/lib/grafana/dashboards"

  advanced_web_app:
    image: 'tantsyurasergey/advancedwebapp:1.0.0'
    container_name: 'docker_training_advancedwebapp'
    ports:
      - '5020:5020'
    environment:
      - AdvancedWebApp_ConnectionStrings__AdvancedWebAppDb='Data Source=docker_training_sqlserver;Initial Catalog=AdvancedWebAppDb;User ID=sa;Password=P@ssword123!'
    networks:
      - docker_training_network_advancedwebapp

  sql:
    image: 'mcr.microsoft.com/mssql/server:2017-latest'
    container_name: 'docker_training_sqlserver'
    ports:
      - '14330:1433'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssword123!
    networks:
      - docker_training_network_advancedwebapp
    volumes:
      - "D:/DockerTraining/src/05_Orchestrating_Systems_with_Docker/AdvancedWebApp_Orchestration/SQL/CreateDatabase.sql:/AdvancedWebApp/CreateDatabase.sql"
    command: sh -c '/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P P@ssword123! -i /AdvancedWebApp/CreateDatabase.sql & /opt/mssql/bin/sqlservr'

networks:
  docker_training_network_advancedwebapp:
    name: docker_training_network_advancedwebapp
    driver: bridge