scrape_configs:
- job_name: AdvancedWebApp_Scrape
  scrape_interval: 5s
  scrape_timeout: 4s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - docker_training_advancedwebapp:5020